version: '3.8'
services:
  dotnet_postgres:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_DB: DotNetHomework
      POSTGRES_USER: sa2
      POSTGRES_PASSWORD: 328732aA!nf;gfh
    ports:
      - "5432:5432"

  dotnet_main:
    image: dotnet-web
    ports:
      - "8080:5000"

    build:
      dockerfile: Dotnet.Homeworks.MainProject/Dockerfile
    depends_on:
      - dotnet_postgres

    environment:
      ConnectionStrings__Default : Host=localhost;Database=DotNetHomework;Port=5432;Username=sa2;Password=328732aA!nf;gfh

  

  dotnet_rabbitmq:
    image: rabbitmq:3-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
  #dotnet_minio:
  #  image: minio/minio:latest
  #  
  #dotnet_mongodb:
  #  image: mongo:latest
  #  
  #dotnet_jaeger:
  #  image: jaegertracing/all-in-one:latest
  #  
  dotnet_mailing:
    image: dotnet-mailing
    ports:
      - "8081:5000"
    
    build:
      dockerfile: Dotnet.Homeworks.Mailing.API/Dockerfile
    depends_on:
      - dotnet_rabbitmq
    
  #dotnet_storage:
  #  image: dotnet-web